# This workflow builds and tests an iOS app using GitHub Actions
name: iOS App Build and Test

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode-version: [14.0, 14.1] # Specify versions of Xcode to test against

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Install dependencies
        if: exists('Podfile') # Run if you use CocoaPods
        run: |
          gem install cocoapods
          pod install
        working-directory: ./app/irl # Adjust this if the Podfile is somewhere else

      - name: Build the app
        run: xcodebuild -project irl.xcodeproj -scheme irl -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' build
        working-directory: ./app/irl

      - name: Run tests
        run: xcodebuild test -project irl.xcodeproj -scheme irl -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.0' -enableCodeCoverage YES
        working-directory: ./app/irl
